config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'posts/upcoming' => "posts#upcoming"
  get 'posts/past' => "posts#past"
  resources :posts

  get 'welcome/about' => "welcome#about"

  get 'sessions/new' => "sessions#new"
  post 'sessions/create' => "sessions#create"
  get 'sessions/logout' => "sessions#logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :post

  has_attached_file :image, styles: { large: "900x900>", medium: "300x300>", small: "200x200>", thumb: "100x100>"}, :path => ":rails_root/public/images/:style/:id/:filename", :url  => "/images/:style/:id/:filename"

  do_not_validate_attachment_file_type :image
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :pictures, :dependent => :destroy

  validates :date, presence: true, uniqueness: true
  validates :title, presence: true
  validates :description, presence: true

  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @month_posts = @posts.where("date >= ? AND date <= ?", Time.zone.now.beginning_of_month, Time.zone.now.end_of_month )
    @posts = @posts.sort {|x, y| x.date <=> y.date}
    @month_posts = @month_posts.sort {|x, y| x.date <=> y.date}
    @date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
  end

  def upcoming
    @posts = Post.where("date >= ?", Date.today)
    @posts = @posts.sort {|x, y| x.date <=> y.date}
  end

  def past
    @posts = Post.where("date <= ?", Date.today)
    @posts = @posts.sort {|x, y| y.date <=> x.date}
  end

  def show
    @post = Post.find(params[:id])
    @pictures = @post.pictures
  end

  def new
    @post = Post.new
    render :"posts/new"
  end

  def create
    @post = Post.new(post_params)
    @post.document = params[:post][:document]
    if @post.save
      if params[:images]
        params[:images].each { |image|
          @post.pictures.create(image: image)
        }
      end
      redirect_to :root
    else
      @errors = @post.errors.full_messages
      render :"posts/new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:post][:document]
      @post.document = params[:post][:document]
    end
    if @post.update(post_params)
      if params[:images]
        @post.pictures.destroy_all
        params[:images].each { |image|
          @post.pictures.create(image: image)
        }
      end
      redirect_to :root
    else
      @errors = @post.errors.full_messages
      render :"post/edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :root
  end

  private
  def logged_in?
    session[:user_id] != nil
  end

  def authenticate_user!
    redirect_to root_path unless logged_in?
  end

  def post_params
    params.require(:post).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render "login"
  end

  def create
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to :root
    else
      render "login"
    end
  end

  def logout
    session.clear
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def user_params
    params.require(:user).permit(:full_name, :username, :avatar, :email, :is_mentor, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    session[:user_id] != nil
  end

  def authenticate_user!
    redirect_to root_path unless logged_in?
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Samuel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <%= favicon_link_tag "samuel.png" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
</head>
<body>
  <div id="wrapper">
      <div class="container">
        <div class="row">
          <div>
            <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
              <div class="topstuff">
                <!-- <%= link_to image_tag("samuel.png", :class =>"img-responsive nav-pic"), root_path %> -->
                <h1>
                  <%= link_to image_tag("samuel.png", class: "hidden-xs") + "Samuel", root_path %>
                  <!-- <div id="sam-click"><%= link_to "About", welcome_about_path %> <div id="sam">SAMUEL</div></div> -->
                </h1>
              </div>
            </nav>
          </div>
        </div>
      </div>
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <footer>
      <br>
      <div class="row">
        <p><%= link_to "Copyright", sessions_new_path %> &copy; samuel.xbt@gmail.com </p>
      </div>
    </footer>

  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="jumbotron form-jumbo">
    <%= bootstrap_form_for @post, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.text_field :title, placeholder: "Enter Title" %>
      </div>
      <div class="form-group">
        <%= f.label :pictures %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      </div>
      <div class="form-group">
        <%= f.text_area :description, placeholder: "Write your words" %>
      </div>
      <div class="form-group">
        <%= f.date_field :date %>
      </div>
      <div class="form-group">
        <%= f.file_field :document %>
      </div>
        <%= f.submit "Edit Post" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">


  <br><br>

  <% if logged_in? %>
    <div class="col-md-6">
      <%= link_to "New Post", new_post_path %>
    </div><br>
  <% end %>

  <div id="calendar">
    <h2 id="month">
      <div class="arrows">
        <div class="show-links past">
          <%= link_to "Past", posts_past_path %>
        </div>
        <span class="hidden-xs">
          <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>

          <%=h @date.strftime("%B %Y") %>

          <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m") %>
        </span>

        <div class="show-links future">
          <%= link_to "Future", posts_upcoming_path %>
        </div>
      </div>
    </h2>
    <div class="hidden-xs">
      <%= calendar_for @posts, :year => @date.year, :month => @date.month do |t| %>
        <%= t.head('S', "M", "T", "W", "T", "F", "S") %>
        <%= t.day(:day_method => :date) do |day, posts| %>
          <div class="full-cell">
            <% posts.each do |post| %>
              <div class="date-post jtextfill">
                <%= h(link_to "#{post.title.upcase}", post) %>
              </div>
            <% end %>
            <div class="date-day">
              <%= day.day %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="hidden-sm hidden-md hidden-lg">
    <ul class="mobile-list">
      <% @month_posts.each do |post| %>
      <li class="mobile-link"><%= link_to "#{post.date.strftime('%m/%d/%Y')} - #{post.title} ", post %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="jumbotron form-jumbo">
    <%= bootstrap_form_for @post, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.text_field :title, placeholder: "Enter Title" %>
      </div>
      <div class="form-group">
        <%= f.label :pictures %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      </div>
      <div class="form-group">
        <%= f.text_area :description, placeholder: "Write your words" %>
      </div>
      <div class="form-group">
        <%= f.date_field :date %>
      </div>
      <div class="form-group">
        <%= f.file_field :document %>
      </div>
        <%= f.submit "Create Post" %>
    <% end %>
  </div>
  <%= @errors %>
</div>

app/views/posts/past.html.erb
<h2 class="list-head"> Past Shows </h2>
<div class="gallery-line"></div>
<ul class="mobile-list">
  <% @posts.each do |post| %>
      <li class="mobile-link">
        <%= link_to "#{post.date.strftime("%m/%d/%Y")} - #{post.title}", post%>
      </li>
  <% end %>
</ul>
</div>

app/views/posts/show.html.erb
<% if logged_in? %>
  <div class="col-md-6">
    <%=link_to "Edit Show", edit_post_path %>
  </div>
  <br>
  <div class="col-md-6">
    <%=link_to "Delete Show", @post, :method => :delete, :confirm => "Yo, you sure?" %>
  </div>
<% end %>


<div class="container post-show">
  <h2> <%= @post.title %> </h2>
  <p class="date"> <%= @post.date.strftime("%m/%d/%Y") %> </p>
  <div class="container">
    <div class="row">


        <!-- <h3>Gallery</h3> -->
        <div class="col-lg-8 col-lg-push-2 col-md-6 col-md-push-3 pic-container">
          <% if @post.pictures.length % 4 == 0 %>
            <% @post.pictures.each do |pic| %>
               <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 thumb">
                 <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                   <%= image_tag(pic.image.url(:medium)) %>
                 </a>
              </div>
            <% end %>
          <% elsif @post.pictures.length % 3 == 0 %>
            <% @post.pictures.each do |pic| %>
               <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 thumb">
                 <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                   <%= image_tag(pic.image.url(:small)) %>
                 </a>
              </div>
            <% end %>
          <% elsif @post.pictures.length == 1 %>
            <% @post.pictures.each do |pic| %>
               <div class="col-lg-12 col-md-12 col-xs-12 thumb">
                 <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                   <%= image_tag(pic.image.url(:medium)) %>
                 </a>
              </div>
            <% end %>
            <% elsif @post.pictures.length == 2 %>
              <% @post.pictures.each do |pic| %>
              <div class="col-lg-6 col-md-6 col-xs-12 thumb">
                <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                  <%= image_tag(pic.image.url(:medium)) %>
                </a>
              </div>
              <% end %>
            <% elsif @post.pictures.length == 5 %>
              <% @post.pictures.each do |pic| %>
              <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 thumb col-md-push-1 col-lg-push-1 col-sm-push-1">
                <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                  <%= image_tag(pic.image.url(:medium)) %>
                </a>
              </div>
              <% end %>
            <% else %>
              <% @post.pictures.each do |pic| %>
              <div class="col-lg-2 col-md-2 col-xs-12 thumb">
                <a class= "thumbnail" href="#" data-image-id="" data-toggle="modal" data-image= "<%= pic.image.url%>" data-target="#image-gallery">
                  <%= image_tag(pic.image.url(:medium)) %>
                </a>
              </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>


      <!-- The Modal -->


<div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="image-gallery-title"></h4>
            </div>
            <div class="modal-body">
                <img id="image-gallery-image" class="img-responsive" src="">
            </div>
            <div class="modal-footer">

                <div class="modal-inner-footer">
                    <button type="button" class="btn btn-link" id="show-previous-image">Previous</button>
                </div>

                <div class="modal-inner-footer">
                    <button type="button" id="show-next-image" class="btn btn-link">Next</button>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="pdf">
  <% if @post.document_file_name %>
  <i class="fa fa-file" aria-hidden="true"></i>
  <%= link_to @post.document.original_filename, @post.document.url %>
  <% end %>
</div>
<div class="gallery-line">
</div>
<div class=" col-lg-8 col-lg-push-2 col-md-8 col-md-push-2 description">
  <p> <%= simple_format(@post.description) %> </p>
</div>

app/views/posts/upcoming.html.erb
<h2 class="list-head"> Upcoming Shows </h2>
<div class="gallery-line"></div>
<ul class="mobile-list">
  <% @posts.each do |post| %>
      <li class="mobile-link">
        <%= link_to "#{post.date.strftime("%m/%d/%Y")} - #{post.title}", post%>
      </li>
  <% end %>
</ul>
</div>

app/views/welcome/about.html.erb
THIS IS SAM